name: challenge
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  awesome_notifications: ^0.10.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  # flutter_stripe: ^11.2.0
  get_it: ^8.0.0
  flutter_screenutil: ^5.9.3
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^8.1.6
  iconsax_flutter: ^1.0.0
  animated_bottom_navigation_bar: ^1.3.3
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  shimmer: ^3.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  # flutter_credit_card: ^4.0.1
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.7
  image_picker: ^1.0.0
  easy_date_timeline: ^1.1.3
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.7.0
  google_generative_ai: ^0.4.6
  fl_chart: ^0.69.0
  flutter_stripe: ^11.2.0
  intl: ^0.19.0
  bloc: ^8.1.4
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.0
  auto_size_text: ^3.0.0
  # flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
